######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 23 00:18:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH +=
INCLUDEPATH +=

# Input
HEADERS += ChatWindow.h
SOURCES += ChatWindow.cpp main.cpp
