######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 24 10:12:14 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Window.h
SOURCES += main.cpp Window.cpp
