######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 22 20:44:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += StopWatch.h
SOURCES += main.cpp StopWatch.cpp
