######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 30 15:36:03 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
