######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 23 14:20:27 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Drag2ClipWidget.h
SOURCES += Drag2ClipWidget.cpp main.cpp
