######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 28 13:40:16 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AddressModel.h
SOURCES += AddressModel.cpp main.cpp
