######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 24 08:49:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DirWidget.h
SOURCES += DirWidget.cpp main.cpp
