######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 20 22:53:34 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ConfigWidget.h
SOURCES += ConfigWidget.cpp main.cpp
