######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 30 10:31:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
