######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 22 13:44:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Window.h
SOURCES += main.cpp Window.cpp
