######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 20 19:08:11 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clickSplitter.h
SOURCES += clickSplitter.cpp main.cpp
