######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 9 14:38:20 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
