######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 21 00:21:52 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
