######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 6 18:13:01 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PieWidget.h
SOURCES += main.cpp PieWidget.cpp
