######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 5 12:00:29 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PaintWidget.h
SOURCES += main.cpp PaintWidget.cpp
