######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 7 19:39:42 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += RotationWidget.h
SOURCES += main.cpp RotationWidget.cpp
