######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 29 14:40:35 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AddressModel.h DnDAddressModel.h
SOURCES += AddressModel.cpp DnDAddressModel.cpp main.cpp
